<?php

namespace backend\models;

use Yii;
use yii\helpers\FileHelper;


class Template extends \yii\db\ActiveRecord
{
    public $twig_content;
    public $layout_twig;
    public $index_twig;
    public $error_twig;
    public $add_twig;
    public $categories_twig;
    public $style_css;

    public $twig_files = array (
        'layout_twig' => 'layout.twig',
        'index_twig' => 'index.twig',
        'error_twig' => 'error.twig',
        'add_twig' => 'add.twig',
        'categories_twig' => 'categories.twig',
        'style_css' => 'style.css',
    );

    public static function tableName()
    {
        return 'form';
    }

    public function rules()
    {
        return [
            [['code', 'name'], 'string'],
            [['twig_content', 'layout_twig', 'index_twig', 'error_twig', 'add_twig', 'categories_twig', 'style_css'], 'safe'],
        ];
    }

    public function attributeLabels()
    {
        return [
            'code' => 'Символьный код',
            'name' => 'Название',
            'twig_content' => 'Основной контент (twig)',
            'layout_twig' => 'layout_twig',
            'index_twig' => 'index_twig',
            'error_twig' => 'error_twig',
            'add_twig' => 'add_twig',
            'categories_twig' => 'categories_twig',
            'style_css' => 'style_css',
        ];
    }

    public function beforeSave($insert)
    {
        $attr = $this->attributes;
        $code = $attr['code'];
        if (!empty($code)) {
            if (is_dir($code)) {
                return false;
            } else {

                $twig_files = array (
                    'layout_twig' => 'layout.twig',
                    'index_twig' => 'index.twig',
                    'error_twig' => 'error.twig',
                    'add_twig' => 'add.twig',
                    'categories_twig' => 'categories.twig',
                    'style_css' => 'style.css',
                );
                $partsPath = Yii::getAlias('@app/../frontend/views/page-templates/' . $code . '/');
                FileHelper::createDirectory($partsPath, $mode = 0755, true);
                foreach ($twig_files as $file) {
                    file_put_contents($partsPath . $file, $this->error_twig);
                }
            }
        } else {
            echo ('Что-то пошло не так!');
        }

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
